### PR TITLE
towards #520; refactored to compartmentalize vue frontend engine

### PR DESCRIPTION
**Pull request by sandeep-gh**
Not able to run tests on my local machine. Several systems issues (I am on OpenBSD). Lets see how the tests go.

### CODE REVIEW

**Comment by WolfgangFahl** [comment]
OpenBSD ... good to test the python platform independence. Just a bit off the standard tracks ..

**Comment by sandeep-gh** [comment]
I will try. Sometimes the rabbit hole is just too deep -- some dependencies just don't compile on OpenBSD.

**Comment by sandeep-gh** [comment]
The Build/test fail error doesn't seem like it is due to the commit (at least not in any direct manner): 
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/bin/green", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/green/cmdline.py", line 91, in main
    tempfile.tempdir = None
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/tempfile.py", line 807, in __exit__
    self.cleanup()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/tmpym30imcb'
```

**Comment by WolfgangFahl** [comment]
Let's give it a try and roll back if it's a problem. A merge directly after a release shouldn't be much of a problem.

**Comment by sandeep-gh** [comment]
Cool. Sounds good to me.

**Pull request merged**
