### PR TITLE
Issue520 pluggable frontend

### PR DESCRIPTION
**Pull request by sandeep-gh**
Compartmentalized vue files within templates/js/vue. Paves way for easily adding non-vue frontend engine.

### CODE REVIEW

**Comment by WolfgangFahl** [comment]
Looks promising. You might want to run all tests to make sure the CI doesn't break.

**Comment by sandeep-gh** [comment]
Any way to run the tests locally?

**Comment by WolfgangFahl** [comment]
scripts/test and scripts/test -m is your friend

my jenkins CI has:

```bash
python3.10 -m venv .venv
source .venv/bin/activate
scripts/install
scripts/test
```

**Comment by sandeep-gh** [comment]
Thank you. Let me give it a try.

**Pull request closed without merging**
